# Generated by Django 4.2.7 on 2023-11-20 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_app', '0003_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Likes',
        ),
    ]
